@host=http://localhost:5270

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Miguel",
    "lastName": "Hobak",
    "email": "miguel@hobak.com",
    "password": "Miguel123!"
}